jwt:
  secret: "k2VhH4s5qA1JHf8g0de/Nu1llotqDq5Ldf7K4EKrm0kA9p5lB4r8XZNtD5J9M0xyXkXnO5uXyQg="
  expiration: 86400000

app:
  upload-dir: uploads

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5433/pasantias
    username: postgres
    password: 1004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
